fix: update reporter for changed check result format
The new check result format sometimes uses `null` instead of an empty array.
It can cause the following error to manifest under certain circumstances:

    TypeError: Cannot read properties of null (reading 'length')

This change handles a null value too, preventing the error.